### ISSUE TITLE
Out of date

### ISSUE THREAD

**Issue by Anonymooseable** [amstan/sauerbraten#1]
The repository is no longer in sync with the svn repo. Could you update it please?

**Comment by beppe9000** [comment]
can we edit things hereor it must be done on sourceforge?

**Comment by amstan** [comment]
> can we edit things hereor it must be done on sourceforge?
This is not an official repository. It's a repository i had a while ago so i could use git with the sauer code.
In fact i might as well delete it I haven't updated it in 2 years probably.
